### ISSUE TITLE
Test AI version

### ISSUE THREAD

**Issue by christophechr** [Gang-de-requins/Playfit#5]
Benchmark between versions of yolov8 and yolov11 models specialized in pose estimation from ultralytics

Test image:
![gros_squat](https://github.com/user-attachments/assets/b05d7b7d-5f9b-4d00-8121-cfc706fcdfc0)

Results:
![benchmark_results](https://github.com/user-attachments/assets/b397bad4-c428-40c1-a6ed-e84948a54833)

**Comment by christophechr** [comment]
@Eowiin In this case, do we go for YOLOv11 ?

**Comment by Eowiin** [comment]
> [@Eowiin](https://github.com/Eowiin) In this case, do we go for YOLOv11 ?

Yes, we want to get fastest result without taking too much memory on user's device. In our case, yolo11vn (smallest version of v11 yolo implementation developped by ultralytics) consume less memory than any other versions and get the fastest result.
